#!/usr/bin/env python3
import os
import sys
import subprocess
import yaml  # Requirement: sudo pacman -S python-yaml

# ─────────────────────────────────────────────────────────────────────────────
# 🜂 F.O.R.G.E. - ORCHESTRATOR
# ─────────────────────────────────────────────────────────────────────────────

LORE_MAP = {
    "core":    "ADAMANT (The Frame)",
    "gaming":  "IGNIS (The Power)",
    "dev":     "AETHER (The Intellect)",
    "ai":      "THE ORACLE (Mind)",
    "secrets": "THE VAULT (Memory)"
}

def log(msg, level="INFO"):
    colors = {
        "INFO": "\033[94m",    # Blue
        "WARN": "\033[93m",    # Yellow
        "TITAN": "\033[96m",   # Cyan
        "SUCCESS": "\033[92m", # Green
        "END": "\033[0m"
    }
    print(f"{colors.get(level, '')}  {msg}{colors['END']}")

def section(title):
    print(f"\n\033[1m[{title}]\033[0m")

def load_state():
    if not os.path.exists("forge.yaml"):
        return {"titan_name": "TITAN", "modules": []}
    with open("forge.yaml", "r") as f:
        return yaml.safe_load(f)

def check_filesystem_integrity():
    section("System Verification")
    fs_type = subprocess.getoutput("findmnt -n -o FSTYPE /")
    if "btrfs" in fs_type:
        log("Filesystem: Btrfs detected.", "INFO")
        log(">> Adamant Resilience: ACTIVE", "SUCCESS")
    else:
        log("Filesystem: Non-Btrfs detected.", "WARN")
        log(">> Adamant Resilience: COMPROMISED", "WARN")

    if os.path.exists("/etc/snapper/configs/root"):
        log("Snapshot Engine: Online", "INFO")
    else:
        log("Snapshot Engine: Offline (Run core/filesystem/setup_snapper.sh)", "WARN")

def generate_hyprland_config(active_modules):
    section("Forging Configuration")
    
    base_dir = os.path.abspath("core/hyprland")
    target_conf = os.path.expanduser("~/.config/hypr/hyprland.conf")
    
    config_lines = [
        "# 🜂 TITAN CONFIGURATION (Generated by F.O.R.G.E.)",
        "# DO NOT EDIT. Edit 'user/custom.conf' instead.",
        "",
        f"source = {base_dir}/base.conf",
        f"source = {base_dir}/monitors.conf",
        f"source = {base_dir}/input.conf"
    ]

    for module in active_modules:
        module_path = os.path.abspath(f"modules/{module}/overrides.conf")
        if os.path.exists(module_path):
            lore_name = LORE_MAP.get(module, module.upper())
            log(f"Fusing Aspect: {lore_name}", "TITAN")
            config_lines.append(f"source = {module_path}")

    log("Applying User Soul (Custom Overrides)", "INFO")
    user_conf = os.path.abspath("user/custom.conf")
    config_lines.append(f"source = {user_conf}")

    os.makedirs(os.path.dirname(target_conf), exist_ok=True)
    with open(target_conf, "w") as f:
        f.write("\n".join(config_lines))
    
    log(f"Titan Config written to: {target_conf}", "SUCCESS")

def main():
    print("\n" + "🜂 " * 20)
    print("   INITIATING TITAN PROTOCOL")
    print("🜂 " * 20)

    state = load_state()
    titan_name = state.get("titan_name", "TITAN")
    modules = state.get("modules", [])

    print(f"\nTARGET SYSTEM: {titan_name}")
    
    check_filesystem_integrity()
    generate_hyprland_config(modules)

    print("\n" + "═" * 40)
    print("   FORGE COMPLETE.")
    print("═" * 40 + "\n")

if __name__ == "__main__":
    main()
